language: cpp
sudo: required

matrix:
  include:

    # linux g++
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER='g++-6'
      script:
        - sudo locale-gen "en_US" "ru_RU"
        - make CXX=$COMPILER 

    # linux clang++
    - os: linux
      compiler: clang

      addons:
        apt:
          sources: 
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages: 
            - clang-3.7
            - g++-6
      env: COMPILER='clang++-3.7'
      script:
        - sudo locale-gen "en_US" "ru_RU"
        - make CXX=$COMPILER 

    # mac clang++
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER='clang++'
      script:
        - make CXX=$COMPILER 

