language: cpp
sudo: required

matrix:
  include:

    # linux g++
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER='g++-6'
      script:
        - sudo locale-gen "en_US" "ru_RU"
        - make CXX=$COMPILER 

    # mac clang++
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER='clang++'
      script:
        - make CXX=$COMPILER 

